name: "purchases_flutter_platform_interface"
version: 0.1.0 # maybe make version:  to always match/sync common_version
description: A common platform interface for the purchases_flutter plugin.
repository: https://github.com/RevenueCat/purchases-flutter/purchases_flutter_platform_interface

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  plugin_platform_interface: ^2.0.2


dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^1.0.0
  test: ^1.15.7
